# .github/workflows/test.yml
name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - name: Install dependencies
        run: uv sync --dev
      - name: Run linters and formatters
        run: |
          uv run ruff format --check .
          uv run ruff check .
          uv run pylint .
      - name: Run tests
        run: uv run pytest -v

  check_pr_source:
    name: Check PR Source Branch
    runs-on: ubuntu-latest
    # Only run this check for pull requests targeting the main branch
    if: github.base_ref == 'main' && github.event_name == 'pull_request'
    steps:
      - name: Verify source branch is develop
        run: |
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "Error: Pull requests targeting 'main' must originate from the 'develop' branch."
            exit 1
          else
            echo "Source branch is 'develop'. Check passed."
          fi

  check_pr_version_bump:
    name: Check PR Version Bump
    runs-on: ubuntu-latest
    # Only run this check for pull requests targeting the develop branch
    if: github.base_ref == 'develop' && github.event_name == 'pull_request'
    steps:
      - name: Get version from __about__.py in develop
        id: version_from_develop
        uses: ./.github/workflows/get-version.yml
        with:
          branch-name: "develop"
          file-path: "src/pyhatchery/__about__.py"
      - name: Get version from __about__.py in current PR branch
        id: version_from_current
        uses: ./.github/workflows/get-version.yml
        with:
          branch-name: "${{ github.base_ref }}"
          file-path: "src/pyhatchery/__about__.py"
      - name: Check version bump
        run: |
          current_version="${{ steps.version_from_current.outputs.version }}"
          previous_version="${{ steps.version_from_develop.outputs.version }}"
          if [[ "$current_version" == "$previous_version" ]]; then
            echo "Error: Version bump is required in the pull request. Version '$current_version' has not changed."
            MESSAGE="Error: Version bump is required in the pull request. The current version is \`$current_version\`. Please ensure the version in \`src/pyhatchery/__about__.py\` is incremented in this PR."
            # Post the comment to the PR. ${{ github.event.number }} is the PR number.
            # gh CLI is pre-installed on GitHub-hosted runners and uses GITHUB_TOKEN automatically.
            gh pr comment ${{ github.event.number }} --body "$MESSAGE"
          else
            echo "Version bump detected. Check passed."
          fi
